CREATE TABLE IF NOT EXISTS REQUESTED_RIDES
(
    ID           UUID PRIMARY KEY,
    FROM_NAME    VARCHAR(1000)  NOT NULL,
    TO_NAME      VARCHAR(1000)  NOT NULL,
    CEP_FROM     VARCHAR(255)   NOT NULL,
    CEP_TO       VARCHAR(255)   NOT NULL,
    PRICE        NUMERIC(11, 2) NOT NULL,
    PASSENGER_ID UUID           NOT NULL,
    ACCEPTED    BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_passenger_requested_rides FOREIGN KEY (PASSENGER_ID) REFERENCES account (id)
)
