CREATE TABLE IF NOT EXISTS OUTBOX (
    ID UUID PRIMARY KEY,
    PAYLOAD TEXT NOT NULL,
    SENT BOOLEAN DEFAULT FALSE,
    EXCHANGE VARCHAR(255) NOT NULL,
    DATE_PRODUCE timestamp NOT NULL,
    DATE_CONSUME timestamp,
    ERROR_MESSAGE TEXT,
    HAS_ERROR BOOLEAN DEFAULT FALSE,
    REQUESTED_BY VARCHAR(255) NOT NULL
)
