name: Test Web

on:
  push:
    branches: ['main']
      
jobs:
  build:
    name: Test Phase
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps: 
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
        node-version: ${{ matrix.node-version }}
     - name: Install modules
       working-directory: ./app
       run: npm install
     - name: Run test
       working-directory: ./app
       run: npm run test
       env:
        CI: true

